name: Test Supported Distributions

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  distro-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          [
            debian_10
          ]
    env:
      DISTRO: ${{matrix.distro}}
      PY_COLORS: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r test/requirements.txt

      - name: Test with tox        
        run: tox -c test/tox.${DISTRO}.ini
