name: Test Supported Distributions

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  distro-test:
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        distro:
          - 'debian_10'
          - 'debian_11'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Build test container for ${{ matrix.distro }}
        run: |
          set -e
          docker build --tag "${{ matrix.distro }}:bats" --file "test/${{ matrix.distro }}.Dockerfile" .

      - name: Run test on ${{ matrix.distro }}
        run: |
           docker run -it "${{ matrix.distro }}:bats" test/bats_core/bin/bats /etc/.pihole/test/test_suite.bats
